### ISSUE TITLE
[Bug]: Server crash after updating

### ISSUE THREAD

**Issue by evhub** [Zepalesque/Aether-Redux-Issue-Tracker#131]
### Minecraft Version

1.20.1

### Mod Version

2.0.16c

### Forge/Neoforge Version

47.3.0

### What happened?

After updating from `2.0.16b` to `2.0.16c`, the server crashed on what looks like generating new chunks (not in the aether).

### What was the expected result?

N/A

### Steps to Reproduce

Mod was updated and then the server crashed a short time after a player joined.

### Log Output (if applicable)

https://gist.github.com/evhub/1fdb21d7f1964e316c49ce0502b52d39

### Additional Context/Information

Note that `blueprint` also shows up in the crash report, but [that appears to be unrelated](https://github.com/team-abnormals/blueprint/issues/232).

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
ah yeah this is actually already fixed for 2.0.17 lol
but yeah that should be out actually fairly soon luckily

**Comment by evhub** [comment]
I tried updating to 2.0.17, but now I'm getting a new server crash:
```
[17Jul2024 21:51:07.651] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:625) ~[forge-1.20.1-47.3.0-universal.jar%231898!/:?]
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:571) ~[forge-1.20.1-47.3.0-universal.jar%231898!/:?]
	at net.minecraftforge.registries.GameData.revertTo(GameData.java:285) ~[forge-1.20.1-47.3.0-universal.jar%231898!/:?]
	at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:345) ~[forge-1.20.1-47.3.0-universal.jar%231898!/:?]
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.20.1-47.3.0-universal.jar%231898!/:?]
	at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217) ~[fmlcore-1.20.1-47.3.0.jar%231894!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209) ~[fmlcore-1.20.1-47.3.0.jar%231894!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:209) ~[fmlcore-1.20.1-47.3.0.jar%231894!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.0.jar%231894!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.0.jar%231894!/:?]
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.3.0-universal.jar%231898!/:?]
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%231893!/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
[17Jul2024 21:53:52.592] [bStats-Metrics/WARN] [Bstats-Metrics/]: No captured server found for dedicated server environment, assuming offline mode
```

**Comment by Maxi90909** [comment]
I can agree on this. I updated Aether Redux to v2.0.17 and it crashes on startup. No idea why, since the previous version works perfectly fine.

**Comment by Zepalesque** [comment]
@evhub could you post the full crash report + game log? this on its own seems to be missing some info

**Comment by evhub** [comment]
No actual crash report was generated. Here are all the log files I have: https://gist.github.com/evhub/115f3e023c9e35d1b0b2d4222c0d79a7

**Comment by Zepalesque** [comment]
ah yeah thats a compat issue with delightful then, i sent a pr to them to fix it

**Comment by Zepalesque** [comment]
in that case, this should be fixed then (or at least once delightful updates)
