### ISSUE TITLE
Server Crash on version 1.0.0 Pre-Release 1

### ISSUE THREAD

**Issue by Wave6677** [Zepalesque/Aether-Redux-Issue-Tracker#8]
When installed with the newest Aether release (beta 6.1) on a server, an error is thrown and the server wont start.

`[init] Resolving type given MOHIST
[init] Resolved version given 1.19.4 into 1.19.4
[init] Setting initial memory to 16G and max to 16G
[init] Starting the Minecraft server...

 __    __   ______   __  __   __   ______   ______  
/\ "-./  \ /\  __ \ /\ \_\ \ /\ \ /\  ___\ /\__  _\ 
\ \ \-./\ \\ \ \/\ \\ \  __ \\ \ \\ \___  \\/_/\ \/ 
 \ \_\ \ \_\\ \_____\\ \_\ \_\\ \_\\/\_____\  \ \_\ 
  \/_/  \/_/ \/_____/ \/_/\/_/ \/_/ \/_____/   \/_/ 
                                                    

                                      Welcome to Mohist ! - Mohist Developement Group - 1.19.4-180, Java 61.0
Update in check...
If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
No update found, latest version: (1.19.4-180) current version: (1.19.4-180)
Checking libraries, please wait...
DownloadSource: MOHIST
All libraries are nice :) !
WARN StatusConsoleListener Advanced terminal features are not available in this environment
[08:18:02 INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 45.1.19, --fml.mcVersion, 1.19.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230314.122934]
[08:18:02 INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.8 by Eclipse Adoptium; OS Linux arch amd64 version 5.14.0-284.25.1.el9_2.x86_64
[08:18:03 INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/data/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2392!/ Service=ModLauncher Env=SERVER
[08:18:03 INFO]: Found 12 dependencies adding them to mods collection
[08:18:04 INFO]: Compatibility level set to JAVA_17
[08:18:04 ERROR]: Mixin config rei.mixins.json does not specify "minVersion" property
[08:18:04 INFO]: Launching target 'forgeserver' with arguments []
[08:18:04 INFO]: Loaded configuration file for Canary: 125 options available, 0 override(s) found
[08:18:04 WARN]: Reference map 'nitrogen_internals.refmap.json' for nitrogen_internals.mixins.json could not be read. If this is a development environment you can ignore this message
[08:18:04 ERROR]: Error loading companion plugin class [com.aetherteam.aether.mixin.AetherMixinPlugin] for mixin config [deep_aether.mixins.json]. The plugin may be out of date: ClassNotFoundException:com.aetherteam.aether.mixin.AetherMixinPlugin
java.lang.ClassNotFoundException: com.aetherteam.aether.mixin.AetherMixinPlugin
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.6.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:76) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:706) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.4-45.1.19.jar%23151!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2383!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2383!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2383!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2383!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2383!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2383!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2383!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:96) [mohist-1.19.4-180-server.jar:1.19.4-180]
[08:18:04 WARN]: Reference map 'chiselsandbits.refmap.json' for chisels-and-bits.mixins.json could not be read. If this is a development environment you can ignore this message
[Serene Seasons Transformer]: Transforming m_47480_ (Lnet/minecraft/world/level/LevelReader;Lnet/minecraft/core/BlockPos;Z)Z in net/minecraft/world/level/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming m_47519_ (Lnet/minecraft/world/level/LevelReader;Lnet/minecraft/core/BlockPos;)Z in net/minecraft/world/level/biome/Biome
[Serene Seasons Transformer]: Successfully patched shouldSnow
[08:18:05 INFO]: Mixing server.MixinDedicatedServer from mixins/common/nochatreports.mixins.json into net.minecraft.server.dedicated.DedicatedServer
[08:18:06 INFO]: Mixing common.MixinFriendlyByteBuf from mixins/common/nochatreports.mixins.json into net.minecraft.network.FriendlyByteBuf
[08:18:06 INFO]: Renaming synthetic method lambda$onWriteJsonWithCodec$1(Ljava/lang/Object;Ljava/lang/String;)Lio/netty/handler/codec/EncoderException; to md79e56d$lambda$onWriteJsonWithCodec$1$0 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf
[08:18:06 INFO]: Renaming synthetic method lambda$onReadJsonWithCodec$0(Ljava/lang/String;)Lio/netty/handler/codec/DecoderException; to md79e56d$lambda$onReadJsonWithCodec$0$1 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf
[08:18:06 WARN]: Method overwrite conflict for getHiddenEffect in werewolves.mixins.json:MobEffectInstanceAccessor, previously written by de.teamlapen.vampirism.mixin.MixinMobEffectInstance. Skipping method.
[Serene Seasons Transformer]: Transforming m_47480_ (Lnet/minecraft/world/level/LevelReader;Lnet/minecraft/core/BlockPos;Z)Z in net/minecraft/world/level/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming m_47519_ (Lnet/minecraft/world/level/LevelReader;Lnet/minecraft/core/BlockPos;)Z in net/minecraft/world/level/biome/Biome
[Serene Seasons Transformer]: Successfully patched shouldSnow
[08:18:07 INFO]: Initialized scena-forge
[08:18:07 INFO]: Attempting to load the Modding Legacy supporters list from https://moddinglegacy.com/supporters-changelogs/supporters.txt
[08:18:07 INFO]: KONNICHIWA ZA WARUDO!
[08:18:07 INFO]: Default JVM text encoding is: UTF-8
[08:18:07 INFO]: Forge mod loading, version 45.1.19, for MC 1.19.4 with MCP 20230314.122934
[08:18:07 INFO]: MinecraftForge v45.1.19 Initialized
[08:18:07 INFO]: Reading config file NoChatReports/NCR-Common.json...
[08:18:07 INFO]: Writing config file NoChatReports/NCR-Common.json...
[08:18:07 ERROR]: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
[08:18:07 WARN]: Error loading class: net/minecraft/client/multiplayer/ClientLevel (java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER)
[08:18:07 INFO]: Constructing common components for mod leavesbegone
[08:18:07 INFO]: Disabling Cumulus as it is on server.
[08:18:07 INFO]: Constructing common components for mod mutantmonsters
[08:18:07 ERROR]: Failed to create mod instance. ModID: aether, class com.aetherteam.aether.Aether
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.1.19.jar%23271!/:?]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.1.19.jar%23270!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at com.aetherteam.aether.Aether.<init>(Aether.java:104) ~[aether-1.19.4-1.0.0-beta.6.1-forge.jar%23214!/:1.19.4-1.0.0-beta.6.1-forge]
        ... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.client.multiplayer.ClientLevel
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at com.aetherteam.aether.Aether.<init>(Aether.java:104) ~[aether-1.19.4-1.0.0-beta.6.1-forge.jar%23214!/:1.19.4-1.0.0-beta.6.1-forge]
        ... 14 more
`

Starting a new SMP for my friends and having this mod would be great. Keep me updated if this is an error on my part or if there is a genuine bug in the mod. Thanks :)

**Comment by Zepalesque** [comment]
hmm, is this the full log file? because I’m having a little trouble figuring out where the part where it went wrong is

**Comment by Zepalesque** [comment]
actually wait looking at it again this might be the full log considering that it appears the crash happened when it loaded the main mod class, interestingly it’s the _aether’s_ mod classfile where it crashed

**Comment by Zepalesque** [comment]
but yeah having the log file as an actual file would be helpful so the formatting isn’t as messed up

**Comment by Zepalesque** [comment]
oh also can I see the mod list? since that could help me find if there are any incompatibilities, or if there’s maybe another one of the aether addons out of date since from the log I can’t be _100%_ certain it’s a redux issue, but it’s definitely possible

**Comment by Wave6677** [comment]
Sure thing, i wasnt aware this was a feature lol
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/12602392/latest.log)
[debug.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/12602393/debug.log)
I wasn't having crashing until i updated Lost Aether, Aether Redux and Aether I to the 6.1 beta version and corresponding releases but I'll go ahead and try removing the other aether add ons for troubleshooting to see if its another aether add on causing the issue

and here's the mod list (Version numbers provided by Prism launcher, not sure if they're all exact):
Ad Astra 1.14.1
Additional Structures 4.0.3
The Aether 1.19.4-1.0.0-beta.6.1-forge
Aether: Lost Content 1.1.5
The Aether: Redux 1.19.4
Alex's Mobs 1.22.3
Ancient Aether 0.6.8
AppleSkin 2.4.3
Architectuary 8.2.89
Backpacked 2.1.14
Bad Packets 0.4.2
Balm 6.0.2
Biomes O' Plenty 17.3.0.593
Blue Skies 1.3.25
Botariu, 2.0.5
Canary 0.2.7
Chisels and Bits 1.3.137
ChoiceTheorem's Overhauled Villages 3.2.5
Chunky 1.3.53
Citadel 2.3.4
Cloth Config API 10.1.105
Continuumation 1.19.4-1.0.0
Deep Aehter 1.19.4-1.0.6
Elevator Mod 1.19.4-1.8.12
Enhanced Extinguishing 1.19.4-1.0.0
Example Mod 1.19.4-1.0.1 (? I'm not sure what this one is)Minec
Ferrite Core 5.2.0
Good Night's Sleep 1.3.1
Guide API Village&Pillage 2.2.6 
Immersive Aircraft 0.6.1
KotlinForForge
Leaves Be Gone 6.0.0
libIPN 3.0.2
Minecraft Comes Alive 7.5.9
Minecraft Transit Railway 3.2.2-hotfix-2
Moolands 1.4.1
MTR Station Decorations 3.2.2-1.3.4-enchancement-1
Multiplayer Server Pause 1.1.0
Mutant Monsters 6.0.2
Nemo's Transit Expansion 0.3.3
No Chat Reporting 2.1.6
No Telemetry 1.7.0
Oculus 1.5.2
OpenBlocks Trophes 2.2
Puzzles Lib 6.0.11
Resourceful Lib 1.3.6
ResourcefulConfig 1.2.0
Roughly Enough Items 11.0.651
Serene Seasons 8.3.0.40
Simple Voice Chat 2.4.24
Structure Gel 2.12.0
TerraBlender 2.2.0.168
The Twilight Forest 4.2.1696
Vampirism 1.9.2
Waystones 13.1.0
Werewolves 1.1.0.1
WHTIT 7.6.0

**Comment by Wave6677** [comment]
Update on this, it looks like Redux is the deciding factor. I removed every mod except Redux's dependencies, and Aether itself and it still crashes. Having just the aether makes it load fine.
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/12602540/latest.log)
[debug.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/12602541/debug.log)

**Comment by Zepalesque** [comment]
hmm from what I can tell it seems like maybe somewhere I’m accidentially acceaaing client-side classes from the server which would cause that kind of issue, I’ll look into it and see if I can fix it for the next version

**Comment by Zepalesque** [comment]
Oh jeez, I just uploaded a new version and now realized I forgot to look into this, oops! 😅
I’ll try to get it fixed in the next update (partly because I’d _also_ like to use the mod in a sever lol)

**Comment by Zepalesque** [comment]
uh oops accidentally closed this before testing to make sure the fix works (and before releasing the update)

**Comment by Zepalesque** [comment]
Okay, the update with the fix *should* be out in the next day or two (maybe 3 if porting to 1.20.1 takes longer than I expect)

**Comment by Zepalesque** [comment]
Fixed in version 1.0!
